//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class emstrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal emstrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainInterface.emstrings", typeof(emstrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0} - {1}. Averagin time: {2}, 
        ///CT turns ratio: {3}, VT turns ratio: {4}.
        /// </summary>
        internal static string avg_archive_info {
            get {
                return ResourceManager.GetString("avg_archive_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string caption_device_connect_error {
            get {
                return ResourceManager.GetString("caption_device_connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string caption_error {
            get {
                return ResourceManager.GetString("caption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string caption_information {
            get {
                return ResourceManager.GetString("caption_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately.
        /// </summary>
        internal static string caption_unfortunately {
            get {
                return ResourceManager.GetString("caption_unfortunately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot establish connection with the Device.
        ///Interface: {0} (interface parameters: {1}{2})..
        /// </summary>
        internal static string msg_device_connect_error {
            get {
                return ResourceManager.GetString("msg_device_connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device&apos;s memory contains no archives.
        /// </summary>
        internal static string msg_device_empty {
            get {
                return ResourceManager.GetString("msg_device_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device firmware version is obsolete. The program cannot communicate with it. 
        ///    To get new firmware version apply to the manufacturer..
        /// </summary>
        internal static string msg_device_version_is_old {
            get {
                return ResourceManager.GetString("msg_device_version_is_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get voltage deviation values!.
        /// </summary>
        internal static string msg_error_get_volvalues {
            get {
                return ResourceManager.GetString("msg_error_get_volvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data was entered!.
        /// </summary>
        internal static string msg_invalid_data {
            get {
                return ResourceManager.GetString("msg_invalid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program needs more memory to finish this operation!.
        /// </summary>
        internal static string msg_outofmemory {
            get {
                return ResourceManager.GetString("msg_outofmemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read system information from the Device.
        /// </summary>
        internal static string msg_read_device_info_error {
            get {
                return ResourceManager.GetString("msg_read_device_info_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average values.
        /// </summary>
        internal static string name_avg_full {
            get {
                return ResourceManager.GetString("name_avg_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energotester PQP-A.
        /// </summary>
        internal static string name_device_etpqpa_full {
            get {
                return ResourceManager.GetString("name_device_etpqpa_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string name_dns_full {
            get {
                return ResourceManager.GetString("name_dns_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Quality Parameters.
        /// </summary>
        internal static string name_pke_full {
            get {
                return ResourceManager.GetString("name_pke_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading list of archives....
        /// </summary>
        internal static string str_read_archive_list {
            get {
                return ResourceManager.GetString("str_read_archive_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading archives....
        /// </summary>
        internal static string str_read_archives {
            get {
                return ResourceManager.GetString("str_read_archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string str_ready {
            get {
                return ResourceManager.GetString("str_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the answer from the device....
        /// </summary>
        internal static string str_waiting_answer {
            get {
                return ResourceManager.GetString("str_waiting_answer", resourceCulture);
            }
        }
    }
}
