#ifndef	_SYSDATA_H_
#define	_SYSDATA_H_

//==================================================================================
//==================================================================================
enum
{
	SD_SerialNumber = 0,//0

	// range names
	SD_RangeNameVoltage1,
	SD_RangeNameVoltage2,
	SD_RangeNameVoltage3,
	SD_RangeNameCurrent1,
	SD_RangeNameCurrent2,
	SD_RangeNameCurrent3,
	SD_RangeNameCurrent4,
	SD_RangeNameCurrent5,
	SD_RangeNameCurrent6,
	SD_RangeNameFrequency1,
	SD_RangeNameFrequency2,

	// active range indices
	SD_RangeActiveVoltage,
	SD_RangeActiveCurrent,
	SD_RangeActiveFrequency,

	// calibration 
	SD_Calibration_Voltage1,
	SD_Calibration_Voltage2,
	SD_Calibration_Voltage3,
	SD_Calibration_Current1,
	SD_Calibration_Current2,
	SD_Calibration_Current3,
	SD_Calibration_Current4,
	SD_Calibration_Current5,
	SD_Calibration_Current6,

	// active connection type
	SD_ConnectionActive,

	//
	SD_VoltageTransformation_OBSOLETE,
	SD_CurrentTransformer,
	SD_VoltageTransformationPrimary_OBSOLETE,
	SD_CurrentTransformerPrimary,

	//
	SD_TimeZone,
	SD_DateTimeAutomaticCorrection,
	SD_DateTimeLastCorrection,

	SD_RangeAllowedCurrent1,
	SD_RangeAllowedCurrent2,
	SD_RangeAllowedCurrent3,
	SD_RangeAllowedCurrent4,
	SD_RangeAllowedCurrent5,
	SD_RangeAllowedCurrent6,
	SD_RangeAllowedFrequency1,
	SD_RangeAllowedFrequency2,

	SD_RangeSensorTypeCurrent1,
	SD_RangeSensorTypeCurrent2,
	SD_RangeSensorTypeCurrent3,
	SD_RangeSensorTypeCurrent4,
	SD_RangeSensorTypeCurrent5,
	SD_RangeSensorTypeCurrent6,

	SD_EventLoggerPointer,
	SD_EventLoggerBlock,

	SD_LedMode,
	SD_LedBrightness,
	SD_NominalVoltage,

	SD_Sets,

	SD_MaxLoadsTime_Start1,
	SD_MaxLoadsTime_Stop1,
	SD_MaxLoadsTime_Start2,
	SD_MaxLoadsTime_Stop2,

	SD_ObjectName,
	SD_ObjectName_Latest1,
	SD_ObjectName_Latest2,
	SD_ObjectName_Latest3,
	SD_ObjectName_Latest4,
	SD_ObjectName_Latest5,
	SD_ObjectName_Latest6,
	SD_ObjectName_Latest7,
	SD_ObjectName_Latest8,
	SD_ObjectName_Latest9,
	SD_ObjectName_Latest10,

	SD_MemoryDistribution_3Sec,
	SD_MemoryDistribution_10Min,
	SD_MemoryDistribution_2Hour,
	SD_MemoryDistribution_Oscilloscope,
	SD_MemoryMode_CircularBuffer,

	SD_MeasurementColors,
	SD_ComputerConnection,

	SD_WlanHomeNetworkSSID,
	SD_WlanHomeNetworkSecurityType,
	SD_WlanHomeNetworkSecurityKey,

	SD_VoltageTransformationSecondary_OBSOLETE,

	SD_DipThresholdPercent,
	SD_SwellThresholdPercent,
	SD_InterruptionThresholdPercent,

	SD_MainsSynchronization,

	SD_DipStateUABCN,
	SD_DipStateUABC,
	SD_DipStateUA,
	SD_DipStateUB,
	SD_DipStateUC,
	SD_DipStateUAB,
	SD_DipStateUBC,
	SD_DipStateUCA,

	SD_SwellStateUABCN,
	SD_SwellStateUABC,
	SD_SwellStateUA,
	SD_SwellStateUB,
	SD_SwellStateUC,
	SD_SwellStateUAB,
	SD_SwellStateUBC,
	SD_SwellStateUCA,

	SD_InterruptionStateUABCN,
	SD_InterruptionStateUABC,
	SD_InterruptionStateUA,
	SD_InterruptionStateUB,
	SD_InterruptionStateUC,
	SD_InterruptionStateUAB,
	SD_InterruptionStateUBC,
	SD_InterruptionStateUCA,

	SD_DipStartDateTimeUABCN,
	SD_DipStartDateTimeUABC,
	SD_DipStartDateTimeUA,
	SD_DipStartDateTimeUB,
	SD_DipStartDateTimeUC,
	SD_DipStartDateTimeUAB,
	SD_DipStartDateTimeUBC,
	SD_DipStartDateTimeUCA,

	SD_SwellStartDateTimeUABCN,
	SD_SwellStartDateTimeUABC,
	SD_SwellStartDateTimeUA,
	SD_SwellStartDateTimeUB,
	SD_SwellStartDateTimeUC,
	SD_SwellStartDateTimeUAB,
	SD_SwellStartDateTimeUBC,
	SD_SwellStartDateTimeUCA,

	SD_InterruptionStartDateTimeUABCN,
	SD_InterruptionStartDateTimeUABC,
	SD_InterruptionStartDateTimeUA,
	SD_InterruptionStartDateTimeUB,
	SD_InterruptionStartDateTimeUC,
	SD_InterruptionStartDateTimeUAB,
	SD_InterruptionStartDateTimeUBC,
	SD_InterruptionStartDateTimeUCA,

	SD_DipValueMicrovoltsUABCN,
	SD_DipValueMicrovoltsUABC,
	SD_DipValueMicrovoltsUA,
	SD_DipValueMicrovoltsUB,
	SD_DipValueMicrovoltsUC,
	SD_DipValueMicrovoltsUAB,
	SD_DipValueMicrovoltsUBC,
	SD_DipValueMicrovoltsUCA,

	SD_SwellValueMicrovoltsUABCN,
	SD_SwellValueMicrovoltsUABC,
	SD_SwellValueMicrovoltsUA,
	SD_SwellValueMicrovoltsUB,
	SD_SwellValueMicrovoltsUC,
	SD_SwellValueMicrovoltsUAB,
	SD_SwellValueMicrovoltsUBC,
	SD_SwellValueMicrovoltsUCA,

	SD_InterruptionValueMicrovoltsUABCN,
	SD_InterruptionValueMicrovoltsUABC,
	SD_InterruptionValueMicrovoltsUA,
	SD_InterruptionValueMicrovoltsUB,
	SD_InterruptionValueMicrovoltsUC,
	SD_InterruptionValueMicrovoltsUAB,
	SD_InterruptionValueMicrovoltsUBC,
	SD_InterruptionValueMicrovoltsUCA,

	SD_DipSwellInterruptionID,

	SD_AdcFrequencyCalibration,
	SD_AdcFrequencyCalibrationNotAllowed,

	SD_DateTimeVerificationSound,
	SD_VoltageTransformerEnable,
	SD_VoltageTransformerType,
	SD_DeclaredVoltage,
	SD_DeclaredVoltageMin,
	SD_DeclaredVoltageMax,

	SD_SupplySystem,

//{
		SD_SetsUser1_FrequencyDeviationSynchronizedDown95,
		SD_SetsUser1_FrequencyDeviationSynchronizedDown100,
		SD_SetsUser1_FrequencyDeviationSynchronizedUp95,
		SD_SetsUser1_FrequencyDeviationSynchronizedUp100,
		SD_SetsUser1_FrequencyDeviationIsolatedDown95,
		SD_SetsUser1_FrequencyDeviationIsolatedDown100,
		SD_SetsUser1_FrequencyDeviationIsolatedUp95,
		SD_SetsUser1_FrequencyDeviationIsolatedUp100,
		SD_SetsUser1_VoltageDeviationPositive95,
		SD_SetsUser1_VoltageDeviationPositive100,
		SD_SetsUser1_FlickerShortTerm95,
		SD_SetsUser1_FlickerShortTerm100,
		SD_SetsUser1_FlickerLongTerm95,
		SD_SetsUser1_FlickerLongTerm100,

		SD_SetsUser1_KHarm95_02,
		SD_SetsUser1_KHarm95_03,
		SD_SetsUser1_KHarm95_04,
		SD_SetsUser1_KHarm95_05,
		SD_SetsUser1_KHarm95_06,
		SD_SetsUser1_KHarm95_07,
		SD_SetsUser1_KHarm95_08,
		SD_SetsUser1_KHarm95_09,
		SD_SetsUser1_KHarm95_10,
		SD_SetsUser1_KHarm95_11,
		SD_SetsUser1_KHarm95_12,
		SD_SetsUser1_KHarm95_13,
		SD_SetsUser1_KHarm95_14,
		SD_SetsUser1_KHarm95_15,
		SD_SetsUser1_KHarm95_16,
		SD_SetsUser1_KHarm95_17,
		SD_SetsUser1_KHarm95_18,
		SD_SetsUser1_KHarm95_19,
		SD_SetsUser1_KHarm95_20,
		SD_SetsUser1_KHarm95_21,
		SD_SetsUser1_KHarm95_22,
		SD_SetsUser1_KHarm95_23,
		SD_SetsUser1_KHarm95_24,
		SD_SetsUser1_KHarm95_25,
		SD_SetsUser1_KHarm95_26,
		SD_SetsUser1_KHarm95_27,
		SD_SetsUser1_KHarm95_28,
		SD_SetsUser1_KHarm95_29,
		SD_SetsUser1_KHarm95_30,
		SD_SetsUser1_KHarm95_31,
		SD_SetsUser1_KHarm95_32,
		SD_SetsUser1_KHarm95_33,
		SD_SetsUser1_KHarm95_34,
		SD_SetsUser1_KHarm95_35,
		SD_SetsUser1_KHarm95_36,
		SD_SetsUser1_KHarm95_37,
		SD_SetsUser1_KHarm95_38,
		SD_SetsUser1_KHarm95_39,
		SD_SetsUser1_KHarm95_40,

		SD_SetsUser1_KHarm100_02,
		SD_SetsUser1_KHarm100_03,
		SD_SetsUser1_KHarm100_04,
		SD_SetsUser1_KHarm100_05,
		SD_SetsUser1_KHarm100_06,
		SD_SetsUser1_KHarm100_07,
		SD_SetsUser1_KHarm100_08,
		SD_SetsUser1_KHarm100_09,
		SD_SetsUser1_KHarm100_10,
		SD_SetsUser1_KHarm100_11,
		SD_SetsUser1_KHarm100_12,
		SD_SetsUser1_KHarm100_13,
		SD_SetsUser1_KHarm100_14,
		SD_SetsUser1_KHarm100_15,
		SD_SetsUser1_KHarm100_16,
		SD_SetsUser1_KHarm100_17,
		SD_SetsUser1_KHarm100_18,
		SD_SetsUser1_KHarm100_19,
		SD_SetsUser1_KHarm100_20,
		SD_SetsUser1_KHarm100_21,
		SD_SetsUser1_KHarm100_22,
		SD_SetsUser1_KHarm100_23,
		SD_SetsUser1_KHarm100_24,
		SD_SetsUser1_KHarm100_25,
		SD_SetsUser1_KHarm100_26,
		SD_SetsUser1_KHarm100_27,
		SD_SetsUser1_KHarm100_28,
		SD_SetsUser1_KHarm100_29,
		SD_SetsUser1_KHarm100_30,
		SD_SetsUser1_KHarm100_31,
		SD_SetsUser1_KHarm100_32,
		SD_SetsUser1_KHarm100_33,
		SD_SetsUser1_KHarm100_34,
		SD_SetsUser1_KHarm100_35,
		SD_SetsUser1_KHarm100_36,
		SD_SetsUser1_KHarm100_37,
		SD_SetsUser1_KHarm100_38,
		SD_SetsUser1_KHarm100_39,
		SD_SetsUser1_KHarm100_40,

		SD_SetsUser1_KHarmTotal95,
		SD_SetsUser1_KHarmTotal100,
		SD_SetsUser1_K2U95,
		SD_SetsUser1_K2U100,
		SD_SetsUser1_K0U95,
		SD_SetsUser1_K0U100,
		SD_SetsUser1_CheckSum,
//}
//{
		SD_SetsUser2_FrequencyDeviationSynchronizedDown95,
		SD_SetsUser2_FrequencyDeviationSynchronizedDown100,
		SD_SetsUser2_FrequencyDeviationSynchronizedUp95,
		SD_SetsUser2_FrequencyDeviationSynchronizedUp100,
		SD_SetsUser2_FrequencyDeviationIsolatedDown95,
		SD_SetsUser2_FrequencyDeviationIsolatedDown100,
		SD_SetsUser2_FrequencyDeviationIsolatedUp95,
		SD_SetsUser2_FrequencyDeviationIsolatedUp100,
		SD_SetsUser2_VoltageDeviationPositive95,
		SD_SetsUser2_VoltageDeviationPositive100,
		SD_SetsUser2_FlickerShortTerm95,
		SD_SetsUser2_FlickerShortTerm100,
		SD_SetsUser2_FlickerLongTerm95,
		SD_SetsUser2_FlickerLongTerm100,

		SD_SetsUser2_KHarm95_02,
		SD_SetsUser2_KHarm95_03,
		SD_SetsUser2_KHarm95_04,
		SD_SetsUser2_KHarm95_05,
		SD_SetsUser2_KHarm95_06,
		SD_SetsUser2_KHarm95_07,
		SD_SetsUser2_KHarm95_08,
		SD_SetsUser2_KHarm95_09,
		SD_SetsUser2_KHarm95_10,
		SD_SetsUser2_KHarm95_11,
		SD_SetsUser2_KHarm95_12,
		SD_SetsUser2_KHarm95_13,
		SD_SetsUser2_KHarm95_14,
		SD_SetsUser2_KHarm95_15,
		SD_SetsUser2_KHarm95_16,
		SD_SetsUser2_KHarm95_17,
		SD_SetsUser2_KHarm95_18,
		SD_SetsUser2_KHarm95_19,
		SD_SetsUser2_KHarm95_20,
		SD_SetsUser2_KHarm95_21,
		SD_SetsUser2_KHarm95_22,
		SD_SetsUser2_KHarm95_23,
		SD_SetsUser2_KHarm95_24,
		SD_SetsUser2_KHarm95_25,
		SD_SetsUser2_KHarm95_26,
		SD_SetsUser2_KHarm95_27,
		SD_SetsUser2_KHarm95_28,
		SD_SetsUser2_KHarm95_29,
		SD_SetsUser2_KHarm95_30,
		SD_SetsUser2_KHarm95_31,
		SD_SetsUser2_KHarm95_32,
		SD_SetsUser2_KHarm95_33,
		SD_SetsUser2_KHarm95_34,
		SD_SetsUser2_KHarm95_35,
		SD_SetsUser2_KHarm95_36,
		SD_SetsUser2_KHarm95_37,
		SD_SetsUser2_KHarm95_38,
		SD_SetsUser2_KHarm95_39,
		SD_SetsUser2_KHarm95_40,

		SD_SetsUser2_KHarm100_02,
		SD_SetsUser2_KHarm100_03,
		SD_SetsUser2_KHarm100_04,
		SD_SetsUser2_KHarm100_05,
		SD_SetsUser2_KHarm100_06,
		SD_SetsUser2_KHarm100_07,
		SD_SetsUser2_KHarm100_08,
		SD_SetsUser2_KHarm100_09,
		SD_SetsUser2_KHarm100_10,
		SD_SetsUser2_KHarm100_11,
		SD_SetsUser2_KHarm100_12,
		SD_SetsUser2_KHarm100_13,
		SD_SetsUser2_KHarm100_14,
		SD_SetsUser2_KHarm100_15,
		SD_SetsUser2_KHarm100_16,
		SD_SetsUser2_KHarm100_17,
		SD_SetsUser2_KHarm100_18,
		SD_SetsUser2_KHarm100_19,
		SD_SetsUser2_KHarm100_20,
		SD_SetsUser2_KHarm100_21,
		SD_SetsUser2_KHarm100_22,
		SD_SetsUser2_KHarm100_23,
		SD_SetsUser2_KHarm100_24,
		SD_SetsUser2_KHarm100_25,
		SD_SetsUser2_KHarm100_26,
		SD_SetsUser2_KHarm100_27,
		SD_SetsUser2_KHarm100_28,
		SD_SetsUser2_KHarm100_29,
		SD_SetsUser2_KHarm100_30,
		SD_SetsUser2_KHarm100_31,
		SD_SetsUser2_KHarm100_32,
		SD_SetsUser2_KHarm100_33,
		SD_SetsUser2_KHarm100_34,
		SD_SetsUser2_KHarm100_35,
		SD_SetsUser2_KHarm100_36,
		SD_SetsUser2_KHarm100_37,
		SD_SetsUser2_KHarm100_38,
		SD_SetsUser2_KHarm100_39,
		SD_SetsUser2_KHarm100_40,

		SD_SetsUser2_KHarmTotal95,
		SD_SetsUser2_KHarmTotal100,
		SD_SetsUser2_K2U95,
		SD_SetsUser2_K2U100,
		SD_SetsUser2_K0U95,
		SD_SetsUser2_K0U100,
		SD_SetsUser2_CheckSum,
//}
		SD_CalibrationUpdate,
		SD_RangeUpdate,
		SD_FirmwareVersion,

		SD_RegistrationMode,
		SD_RegistrationScheduledStartDateTime,
		SD_RegistrationScheduledStopDateTime,
		SD_RegistrationManualStart,
		SD_RegistrationManualStartDateTime,

		SD_FirmwareIteration,

		SD_RegistrationArchiveIntervals,

		SD_RegistrationIndex,

		SD_Password1stLevelHash,
		SD_Password2ndLevelHash,
		SD_MenuAutomaticLock,

		SD_FirmwareVersionBootloader,

		SD_NandInvalidBlockCounter,
		SD_RegistrationArchiveIndex,

		SD_RegistrationArchiveLengthSec1,
		SD_RegistrationArchiveLengthSec2,

		SD_UsbTraceEnable,

		SD_AverageArchiveIndex_3Sec,
		SD_AverageArchiveIndex_10Min,
		SD_AverageArchiveIndex_2Hour,

		SD_DspSupervisor,

		SD_SetsUser1_VoltageDeviationNegative95,
		SD_SetsUser1_VoltageDeviationNegative100,
		SD_SetsUser2_VoltageDeviationNegative95,
		SD_SetsUser2_VoltageDeviationNegative100,

		SD_MenuLanguage,
		SD_EnegryArchiveIndex,
		SD_PasswordEnable,

	SD_SynchroMeasurements_Duration,
	SD_SynchroMeasurements_StartDateTime,

	SD_SynchroMeasurementsArchiveIndex,

	SD_FlexClampsSelfPowered,
	SD_LanguageChangeEnable,

	SD_Flickermeter,

	SD_Password0thLevelHash,

	SD_UsbModule_Interface,
	SD_UsbModule_LAN_AddressMode,
	SD_UsbModule_WLAN_AddressMode,
	SD_UsbModule_WLAN_Mode,
	SD_UsbModule_WLAN_AP_Passphrase,
	SD_UsbModule_WLAN_AP_IP,
	SD_UsbModule_WLAN_AP_Mask,
	SD_UsbModule_WLAN_AP_DhcpStart,
	SD_UsbModule_WLAN_AP_DhcpEnd,

	SD_DeviceClass,

	SD_UsbModule_WLAN_Client_Ssid,
	SD_UsbModule_WLAN_Client_Passphrase,

	SD_FlaggedData,

	SD_LAST
};
//==================================================================================
//==================================================================================
//enum
//{
//	SDTYPE_WORD=0,
//	SDTYPE_ENUM,
//	SDTYPE_LONG, // signed 32 bit integer
//	SDTYPE_FLOAT, // single 32 bit float
//	SDTYPE_CALIBRATION, // 4xlong + 4xlong + 4xfloat + 4xfloat = 64bytes
//	SDTYPE_BOOL,
//	SDTYPE_DATETIME,
//	SDTYPE_DWORD,
//	SDTYPE_CHAR16,
//	SDTYPE_SZ64,
//	SDTYPE_COMMAND,
//
//	SDTYPE_MAX
//};

//const BYTE abSysDataTypeSizeWords[SDTYPE_MAX] = {
//	1,//SDTYPE_WORD
//	1,//SDTYPE_ENUM
//	2,//SDTYPE_LONG
//	2,//SDTYPE_FLOAT
//	40,//SDTYPE_CALIBRATION
//	1,//SDTYPE_BOOL
//	14,//SDTYPE_DATETIME (TDateTime)
//	2,//SDTYPE_DWORD
//	16/2,//SDTYPE_CHAR16
//	64/2,//SDTYPE_SZ64
//	1,//SDTYPE_COMMAND
//};

//enum
//{
//	SDACCESS_READONLY = 0,
//	SDACCESS_USER,
//	SDACCESS_MARSENERGO
//};

//#define		PQPA_TRUE				(0)
//#define		PQPA_FALSE				(1)

//==================================================================================
//==================================================================================
//typedef struct
//{
//	WORD wIndex;
//	WORD wType;
//	WORD wAccess;
//	char szTitle[64];
//} TSysData;
//==================================================================================
//==================================================================================
//const TSysData xSysData[SD_LAST] = 
//{
//	SD_SerialNumber,
//		SDTYPE_WORD,SDACCESS_USER,"SD_SerialNumber\0",
//
//	SD_RangeNameVoltage1,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameVoltage1\0",
//	SD_RangeNameVoltage2,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameVoltage2\0",
//	SD_RangeNameVoltage3,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameVoltage3\0",
//	SD_RangeNameCurrent1,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameCurrent1\0",
//	SD_RangeNameCurrent2,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameCurrent2\0",
//	SD_RangeNameCurrent3,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameCurrent3\0",
//	SD_RangeNameCurrent4,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameCurrent4\0",
//	SD_RangeNameCurrent5,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameCurrent5\0",
//	SD_RangeNameCurrent6,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameCurrent6\0",
//	SD_RangeNameFrequency1,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameFrequency1\0",
//	SD_RangeNameFrequency2,
//		SDTYPE_WORD,SDACCESS_USER,"SD_RangeNameFrequency2\0",
//
//	SD_RangeActiveVoltage,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeActiveVoltage\0",
//	SD_RangeActiveCurrent,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeActiveCurrent\0",
//	SD_RangeActiveFrequency,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeActiveFrequency\0",
//
//	SD_Calibration_Voltage1,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Voltage1\0",
//	SD_Calibration_Voltage2,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Voltage2\0",
//	SD_Calibration_Voltage3,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Voltage3\0",
//	SD_Calibration_Current1,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Current1\0",
//	SD_Calibration_Current2,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Current2\0",
//	SD_Calibration_Current3,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Current3\0",
//	SD_Calibration_Current4,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Current4\0",
//	SD_Calibration_Current5,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Current5\0",
//	SD_Calibration_Current6,
//		SDTYPE_CALIBRATION,SDACCESS_USER,"SD_Calibration_Current6\0",
//
//	SD_ConnectionActive,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_ConnectionActive\0",
//
//	SD_VoltageTransformation_OBSOLETE,
//		SDTYPE_ENUM,/*SDACCESS_USER*/SDACCESS_READONLY,"SD_VoltageTransformation_OBSOLETE\0",
//	SD_CurrentTransformer,
//		SDTYPE_WORD,SDACCESS_USER,"SD_CurrentTransformer\0",
//	SD_VoltageTransformationPrimary_OBSOLETE,
//		SDTYPE_DWORD,/*SDACCESS_USER*/SDACCESS_READONLY,"SD_VoltageTransformationPrimary_OBSOLETE\0",
//	SD_CurrentTransformerPrimary,
//		SDTYPE_WORD,SDACCESS_USER,"SD_CurrentTransformerPrimary\0",
//
//	SD_TimeZone,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_TimeZone\0",
//	SD_DateTimeAutomaticCorrection,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_DateTimeAutomaticCorrection\0",
//
//	SD_DateTimeLastCorrection,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DateTimeLastCorrection\0",
//
//	SD_RangeAllowedCurrent1,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedCurrent1\0",
//	SD_RangeAllowedCurrent2,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedCurrent2\0",
//	SD_RangeAllowedCurrent3,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedCurrent3\0",
//	SD_RangeAllowedCurrent4,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedCurrent4\0",
//	SD_RangeAllowedCurrent5,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedCurrent5\0",
//	SD_RangeAllowedCurrent6,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedCurrent6\0",
//	SD_RangeAllowedFrequency1,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedFrequency1\0",
//	SD_RangeAllowedFrequency2,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RangeAllowedFrequency2\0",
//
//	SD_RangeSensorTypeCurrent1,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeSensorTypeCurrent1\0",
//	SD_RangeSensorTypeCurrent2,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeSensorTypeCurrent2\0",
//	SD_RangeSensorTypeCurrent3,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeSensorTypeCurrent3\0",
//	SD_RangeSensorTypeCurrent4,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeSensorTypeCurrent4\0",
//	SD_RangeSensorTypeCurrent5,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeSensorTypeCurrent5\0",
//	SD_RangeSensorTypeCurrent6,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RangeSensorTypeCurrent6\0",
//
//	SD_EventLoggerPointer,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_EventLoggerPointer\0",
//	SD_EventLoggerBlock,
//		SDTYPE_WORD,SDACCESS_READONLY,"SD_EventLoggerBlock\0",
//
//	SD_LedMode,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_LedMode\0",
//	SD_LedBrightness,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_LedBrightness\0",
//
//	SD_NominalVoltage,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_NominalVoltage\0",
//
//	SD_Sets,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_Sets\0",
//
//	SD_MaxLoadsTime_Start1,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MaxLoadsTime_Start1\0",
//	SD_MaxLoadsTime_Stop1,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MaxLoadsTime_Stop1\0",
//	SD_MaxLoadsTime_Start2,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MaxLoadsTime_Start2\0",
//	SD_MaxLoadsTime_Stop2,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MaxLoadsTime_Stop2\0",
//
//	SD_ObjectName,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName\0",
//	SD_ObjectName_Latest1,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest1\0",
//	SD_ObjectName_Latest2,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest2\0",
//	SD_ObjectName_Latest3,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest3\0",
//	SD_ObjectName_Latest4,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest4\0",
//	SD_ObjectName_Latest5,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest5\0",
//	SD_ObjectName_Latest6,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest6\0",
//	SD_ObjectName_Latest7,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest7\0",
//	SD_ObjectName_Latest8,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest8\0",
//	SD_ObjectName_Latest9,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest9\0",
//	SD_ObjectName_Latest10,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_ObjectName_Latest10\0",
//
//	SD_MemoryDistribution_3Sec,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MemoryDistribution_3Sec\0",
//	SD_MemoryDistribution_10Min,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MemoryDistribution_10Min\0",
//	SD_MemoryDistribution_2Hour,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MemoryDistribution_2Hour\0",
//	SD_MemoryDistribution_Oscilloscope,
//		SDTYPE_WORD,SDACCESS_USER,"SD_MemoryDistribution_Oscilloscope\0",
//	SD_MemoryMode_CircularBuffer,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_MemoryMode_CircularBuffer\0",
//
//	SD_MeasurementColors,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_MeasurementColors\0",
//	SD_ComputerConnection,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_ComputerConnection\0",
//
//	SD_WlanHomeNetworkSSID,
//		SDTYPE_SZ64,SDACCESS_USER,"SD_WlanHomeNetworkSSID\0",
//	SD_WlanHomeNetworkSecurityType,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_WlanHomeNetworkSecurityType\0",
//	SD_WlanHomeNetworkSecurityKey,
//		SDTYPE_SZ64,SDACCESS_USER,"SD_WlanHomeNetworkSecurityKey\0",
//
//	SD_VoltageTransformationSecondary_OBSOLETE,
//		SDTYPE_WORD,/*SDACCESS_USER*/SDACCESS_READONLY,"SD_VoltageTransformationSecondary_OBSOLETE\0",
//
//	SD_DipThresholdPercent,
//		SDTYPE_WORD,SDACCESS_USER,"SD_DipThresholdPercent\0",
//	SD_SwellThresholdPercent,
//		SDTYPE_WORD,SDACCESS_USER,"SD_SwellThresholdPercent\0",
//	SD_InterruptionThresholdPercent,
//		SDTYPE_WORD,SDACCESS_USER,"SD_InterruptionThresholdPercent\0",
//
//	SD_MainsSynchronization,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_MainsSynchronization\0",
//
//	SD_DipStateUABCN,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUABCN\0",
//	SD_DipStateUABC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUABC\0",
//	SD_DipStateUA,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUA\0",
//	SD_DipStateUB,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUB\0",
//	SD_DipStateUC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUC\0",
//	SD_DipStateUAB,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUAB\0",
//	SD_DipStateUBC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUBC\0",
//	SD_DipStateUCA,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_DipStateUCA\0",
//
//	SD_SwellStateUABCN,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUABCN\0",
//	SD_SwellStateUABC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUABC\0",
//	SD_SwellStateUA,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUA\0",
//	SD_SwellStateUB,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUB\0",
//	SD_SwellStateUC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUC\0",
//	SD_SwellStateUAB,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUAB\0",
//	SD_SwellStateUBC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUBC\0",
//	SD_SwellStateUCA,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_SwellStateUCA\0",
//
//	SD_InterruptionStateUABCN,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUABCN\0",
//	SD_InterruptionStateUABC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUABC\0",
//	SD_InterruptionStateUA,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUA\0",
//	SD_InterruptionStateUB,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUB\0",
//	SD_InterruptionStateUC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUC\0",
//	SD_InterruptionStateUAB,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUAB\0",
//	SD_InterruptionStateUBC,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUBC\0",
//	SD_InterruptionStateUCA,
//		SDTYPE_BOOL,SDACCESS_READONLY,"SD_InterruptionStateUCA\0",
//
//	SD_DipStartDateTimeUABCN,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUABCN\0",
//	SD_DipStartDateTimeUABC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUABC\0",
//	SD_DipStartDateTimeUA,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUA\0",
//	SD_DipStartDateTimeUB,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUB\0",
//	SD_DipStartDateTimeUC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUC\0",
//	SD_DipStartDateTimeUAB,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUAB\0",
//	SD_DipStartDateTimeUBC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUBC\0",
//	SD_DipStartDateTimeUCA,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_DipStartDateTimeUCA\0",
//
//	SD_SwellStartDateTimeUABCN,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUABCN\0",
//	SD_SwellStartDateTimeUABC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUABC\0",
//	SD_SwellStartDateTimeUA,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUA\0",
//	SD_SwellStartDateTimeUB,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUB\0",
//	SD_SwellStartDateTimeUC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUC\0",
//	SD_SwellStartDateTimeUAB,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUAB\0",
//	SD_SwellStartDateTimeUBC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUBC\0",
//	SD_SwellStartDateTimeUCA,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SwellStartDateTimeUCA\0",
//
//	SD_InterruptionStartDateTimeUABCN,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUABCN\0",
//	SD_InterruptionStartDateTimeUABC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUABC\0",
//	SD_InterruptionStartDateTimeUA,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUA\0",
//	SD_InterruptionStartDateTimeUB,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUB\0",
//	SD_InterruptionStartDateTimeUC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUC\0",
//	SD_InterruptionStartDateTimeUAB,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUAB\0",
//	SD_InterruptionStartDateTimeUBC,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUBC\0",
//	SD_InterruptionStartDateTimeUCA,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_InterruptionStartDateTimeUCA\0",
//
//	SD_DipValueMicrovoltsUABCN,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUABCN\0",
//	SD_DipValueMicrovoltsUABC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUABC\0",
//	SD_DipValueMicrovoltsUA,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUA\0",
//	SD_DipValueMicrovoltsUB,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUB\0",
//	SD_DipValueMicrovoltsUC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUC\0",
//	SD_DipValueMicrovoltsUAB,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUAB\0",
//	SD_DipValueMicrovoltsUBC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUBC\0",
//	SD_DipValueMicrovoltsUCA,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipValueMicrovoltsUCA\0",
//
//	SD_SwellValueMicrovoltsUABCN,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUABCN\0",
//	SD_SwellValueMicrovoltsUABC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUABC\0",
//	SD_SwellValueMicrovoltsUA,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUA\0",
//	SD_SwellValueMicrovoltsUB,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUB\0",
//	SD_SwellValueMicrovoltsUC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUC\0",
//	SD_SwellValueMicrovoltsUAB,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUAB\0",
//	SD_SwellValueMicrovoltsUBC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUBC\0",
//	SD_SwellValueMicrovoltsUCA,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SwellValueMicrovoltsUCA\0",
//
//	SD_InterruptionValueMicrovoltsUABCN,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUABCN\0",
//	SD_InterruptionValueMicrovoltsUABC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUABC\0",
//	SD_InterruptionValueMicrovoltsUA,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUA\0",
//	SD_InterruptionValueMicrovoltsUB,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUB\0",
//	SD_InterruptionValueMicrovoltsUC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUC\0",
//	SD_InterruptionValueMicrovoltsUAB,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUAB\0",
//	SD_InterruptionValueMicrovoltsUBC,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUBC\0",
//	SD_InterruptionValueMicrovoltsUCA,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_InterruptionValueMicrovoltsUCA\0",
//
//	SD_DipSwellInterruptionID,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_DipSwellInterruptionID\0",
//
//	SD_AdcFrequencyCalibration,
//		SDTYPE_FLOAT,SDACCESS_MARSENERGO,"SD_AdcFrequencyCalibration\0",
//	SD_AdcFrequencyCalibrationNotAllowed,
//		SDTYPE_BOOL,SDACCESS_MARSENERGO,"SD_AdcFrequencyCalibrationNotAllowed\0",
//
//	SD_DateTimeVerificationSound,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_DateTimeVerificationSound\0",
//
//	SD_VoltageTransformerEnable,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_VoltageTransformerEnable\0",
//	SD_VoltageTransformerType,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_VoltageTransformerType\0",
//
//	SD_DeclaredVoltage,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_DeclaredVoltage\0",
//	SD_DeclaredVoltageMin,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_DeclaredVoltageMin\0",
//	SD_DeclaredVoltageMax,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_DeclaredVoltageMax\0",
//
//	SD_SupplySystem,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_SupplySystem\0",
//
////{
//		SD_SetsUser1_FrequencyDeviationSynchronizedDown95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationSynchronizedDown95\0",
//		SD_SetsUser1_FrequencyDeviationSynchronizedDown100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationSynchronizedDown100\0",
//		SD_SetsUser1_FrequencyDeviationSynchronizedUp95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationSynchronizedUp95\0",
//		SD_SetsUser1_FrequencyDeviationSynchronizedUp100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationSynchronizedUp100\0",
//		SD_SetsUser1_FrequencyDeviationIsolatedDown95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationIsolatedDown95\0",
//		SD_SetsUser1_FrequencyDeviationIsolatedDown100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationIsolatedDown100\0",
//		SD_SetsUser1_FrequencyDeviationIsolatedUp95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationIsolatedUp95\0",
//		SD_SetsUser1_FrequencyDeviationIsolatedUp100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FrequencyDeviationIsolatedUp100\0",
//		SD_SetsUser1_VoltageDeviationPositive95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_VoltageDeviationPositive95\0",
//		SD_SetsUser1_VoltageDeviationPositive100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_VoltageDeviationPositive100\0",
//		SD_SetsUser1_FlickerShortTerm95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FlickerShortTerm95\0",
//		SD_SetsUser1_FlickerShortTerm100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FlickerShortTerm100\0",
//		SD_SetsUser1_FlickerLongTerm95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FlickerLongTerm95\0",
//		SD_SetsUser1_FlickerLongTerm100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_FlickerLongTerm100\0",
//
//		SD_SetsUser1_KHarm95_02,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_02\0",
//		SD_SetsUser1_KHarm95_03,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_03\0",
//		SD_SetsUser1_KHarm95_04,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_04\0",
//		SD_SetsUser1_KHarm95_05,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_05\0",
//		SD_SetsUser1_KHarm95_06,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_06\0",
//		SD_SetsUser1_KHarm95_07,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_07\0",
//		SD_SetsUser1_KHarm95_08,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_08\0",
//		SD_SetsUser1_KHarm95_09,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_09\0",
//		SD_SetsUser1_KHarm95_10,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_10\0",
//		SD_SetsUser1_KHarm95_11,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_11\0",
//		SD_SetsUser1_KHarm95_12,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_12\0",
//		SD_SetsUser1_KHarm95_13,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_13\0",
//		SD_SetsUser1_KHarm95_14,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_14\0",
//		SD_SetsUser1_KHarm95_15,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_15\0",
//		SD_SetsUser1_KHarm95_16,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_16\0",
//		SD_SetsUser1_KHarm95_17,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_17\0",
//		SD_SetsUser1_KHarm95_18,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_18\0",
//		SD_SetsUser1_KHarm95_19,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_19\0",
//		SD_SetsUser1_KHarm95_20,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_20\0",
//		SD_SetsUser1_KHarm95_21,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_21\0",
//		SD_SetsUser1_KHarm95_22,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_22\0",
//		SD_SetsUser1_KHarm95_23,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_23\0",
//		SD_SetsUser1_KHarm95_24,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_24\0",
//		SD_SetsUser1_KHarm95_25,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_25\0",
//		SD_SetsUser1_KHarm95_26,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_26\0",
//		SD_SetsUser1_KHarm95_27,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_27\0",
//		SD_SetsUser1_KHarm95_28,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_28\0",
//		SD_SetsUser1_KHarm95_29,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_29\0",
//		SD_SetsUser1_KHarm95_30,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_30\0",
//		SD_SetsUser1_KHarm95_31,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_31\0",
//		SD_SetsUser1_KHarm95_32,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_32\0",
//		SD_SetsUser1_KHarm95_33,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_33\0",
//		SD_SetsUser1_KHarm95_34,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_34\0",
//		SD_SetsUser1_KHarm95_35,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_35\0",
//		SD_SetsUser1_KHarm95_36,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_36\0",
//		SD_SetsUser1_KHarm95_37,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_37\0",
//		SD_SetsUser1_KHarm95_38,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_38\0",
//		SD_SetsUser1_KHarm95_39,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_39\0",
//		SD_SetsUser1_KHarm95_40,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm95_40\0",
//
//		SD_SetsUser1_KHarm100_02,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_02\0",
//		SD_SetsUser1_KHarm100_03,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_03\0",
//		SD_SetsUser1_KHarm100_04,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_04\0",
//		SD_SetsUser1_KHarm100_05,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_05\0",
//		SD_SetsUser1_KHarm100_06,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_06\0",
//		SD_SetsUser1_KHarm100_07,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_07\0",
//		SD_SetsUser1_KHarm100_08,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_08\0",
//		SD_SetsUser1_KHarm100_09,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_09\0",
//		SD_SetsUser1_KHarm100_10,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_10\0",
//		SD_SetsUser1_KHarm100_11,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_11\0",
//		SD_SetsUser1_KHarm100_12,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_12\0",
//		SD_SetsUser1_KHarm100_13,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_13\0",
//		SD_SetsUser1_KHarm100_14,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_14\0",
//		SD_SetsUser1_KHarm100_15,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_15\0",
//		SD_SetsUser1_KHarm100_16,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_16\0",
//		SD_SetsUser1_KHarm100_17,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_17\0",
//		SD_SetsUser1_KHarm100_18,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_18\0",
//		SD_SetsUser1_KHarm100_19,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_19\0",
//		SD_SetsUser1_KHarm100_20,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_20\0",
//		SD_SetsUser1_KHarm100_21,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_21\0",
//		SD_SetsUser1_KHarm100_22,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_22\0",
//		SD_SetsUser1_KHarm100_23,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_23\0",
//		SD_SetsUser1_KHarm100_24,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_24\0",
//		SD_SetsUser1_KHarm100_25,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_25\0",
//		SD_SetsUser1_KHarm100_26,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_26\0",
//		SD_SetsUser1_KHarm100_27,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_27\0",
//		SD_SetsUser1_KHarm100_28,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_28\0",
//		SD_SetsUser1_KHarm100_29,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_29\0",
//		SD_SetsUser1_KHarm100_30,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_30\0",
//		SD_SetsUser1_KHarm100_31,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_31\0",
//		SD_SetsUser1_KHarm100_32,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_32\0",
//		SD_SetsUser1_KHarm100_33,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_33\0",
//		SD_SetsUser1_KHarm100_34,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_34\0",
//		SD_SetsUser1_KHarm100_35,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_35\0",
//		SD_SetsUser1_KHarm100_36,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_36\0",
//		SD_SetsUser1_KHarm100_37,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_37\0",
//		SD_SetsUser1_KHarm100_38,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_38\0",
//		SD_SetsUser1_KHarm100_39,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_39\0",
//		SD_SetsUser1_KHarm100_40,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarm100_40\0",
//
//		SD_SetsUser1_KHarmTotal95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarmTotal95\0",
//		SD_SetsUser1_KHarmTotal100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_KHarmTotal100\0",
//		SD_SetsUser1_K2U95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_K2U95\0",
//		SD_SetsUser1_K2U100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_K2U100\0",
//		SD_SetsUser1_K0U95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_K0U95\0",
//		SD_SetsUser1_K0U100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_K0U100\0",
//		SD_SetsUser1_CheckSum,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_CheckSum\0",
////}
////{
//		SD_SetsUser2_FrequencyDeviationSynchronizedDown95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationSynchronizedDown95\0",
//		SD_SetsUser2_FrequencyDeviationSynchronizedDown100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationSynchronizedDown100\0",
//		SD_SetsUser2_FrequencyDeviationSynchronizedUp95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationSynchronizedUp95\0",
//		SD_SetsUser2_FrequencyDeviationSynchronizedUp100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationSynchronizedUp100\0",
//		SD_SetsUser2_FrequencyDeviationIsolatedDown95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationIsolatedDown95\0",
//		SD_SetsUser2_FrequencyDeviationIsolatedDown100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationIsolatedDown100\0",
//		SD_SetsUser2_FrequencyDeviationIsolatedUp95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationIsolatedUp95\0",
//		SD_SetsUser2_FrequencyDeviationIsolatedUp100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FrequencyDeviationIsolatedUp100\0",
//		SD_SetsUser2_VoltageDeviationPositive95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_VoltageDeviationPositive95\0",
//		SD_SetsUser2_VoltageDeviationPositive100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_VoltageDeviationPositive100\0",
//		SD_SetsUser2_FlickerShortTerm95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FlickerShortTerm95\0",
//		SD_SetsUser2_FlickerShortTerm100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FlickerShortTerm100\0",
//		SD_SetsUser2_FlickerLongTerm95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FlickerLongTerm95\0",
//		SD_SetsUser2_FlickerLongTerm100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_FlickerLongTerm100\0",
//
//		SD_SetsUser2_KHarm95_02,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_02\0",
//		SD_SetsUser2_KHarm95_03,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_03\0",
//		SD_SetsUser2_KHarm95_04,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_04\0",
//		SD_SetsUser2_KHarm95_05,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_05\0",
//		SD_SetsUser2_KHarm95_06,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_06\0",
//		SD_SetsUser2_KHarm95_07,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_07\0",
//		SD_SetsUser2_KHarm95_08,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_08\0",
//		SD_SetsUser2_KHarm95_09,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_09\0",
//		SD_SetsUser2_KHarm95_10,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_10\0",
//		SD_SetsUser2_KHarm95_11,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_11\0",
//		SD_SetsUser2_KHarm95_12,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_12\0",
//		SD_SetsUser2_KHarm95_13,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_13\0",
//		SD_SetsUser2_KHarm95_14,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_14\0",
//		SD_SetsUser2_KHarm95_15,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_15\0",
//		SD_SetsUser2_KHarm95_16,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_16\0",
//		SD_SetsUser2_KHarm95_17,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_17\0",
//		SD_SetsUser2_KHarm95_18,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_18\0",
//		SD_SetsUser2_KHarm95_19,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_19\0",
//		SD_SetsUser2_KHarm95_20,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_20\0",
//		SD_SetsUser2_KHarm95_21,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_21\0",
//		SD_SetsUser2_KHarm95_22,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_22\0",
//		SD_SetsUser2_KHarm95_23,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_23\0",
//		SD_SetsUser2_KHarm95_24,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_24\0",
//		SD_SetsUser2_KHarm95_25,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_25\0",
//		SD_SetsUser2_KHarm95_26,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_26\0",
//		SD_SetsUser2_KHarm95_27,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_27\0",
//		SD_SetsUser2_KHarm95_28,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_28\0",
//		SD_SetsUser2_KHarm95_29,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_29\0",
//		SD_SetsUser2_KHarm95_30,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_30\0",
//		SD_SetsUser2_KHarm95_31,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_31\0",
//		SD_SetsUser2_KHarm95_32,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_32\0",
//		SD_SetsUser2_KHarm95_33,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_33\0",
//		SD_SetsUser2_KHarm95_34,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_34\0",
//		SD_SetsUser2_KHarm95_35,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_35\0",
//		SD_SetsUser2_KHarm95_36,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_36\0",
//		SD_SetsUser2_KHarm95_37,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_37\0",
//		SD_SetsUser2_KHarm95_38,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_38\0",
//		SD_SetsUser2_KHarm95_39,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_39\0",
//		SD_SetsUser2_KHarm95_40,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm95_40\0",
//
//		SD_SetsUser2_KHarm100_02,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_02\0",
//		SD_SetsUser2_KHarm100_03,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_03\0",
//		SD_SetsUser2_KHarm100_04,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_04\0",
//		SD_SetsUser2_KHarm100_05,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_05\0",
//		SD_SetsUser2_KHarm100_06,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_06\0",
//		SD_SetsUser2_KHarm100_07,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_07\0",
//		SD_SetsUser2_KHarm100_08,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_08\0",
//		SD_SetsUser2_KHarm100_09,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_09\0",
//		SD_SetsUser2_KHarm100_10,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_10\0",
//		SD_SetsUser2_KHarm100_11,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_11\0",
//		SD_SetsUser2_KHarm100_12,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_12\0",
//		SD_SetsUser2_KHarm100_13,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_13\0",
//		SD_SetsUser2_KHarm100_14,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_14\0",
//		SD_SetsUser2_KHarm100_15,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_15\0",
//		SD_SetsUser2_KHarm100_16,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_16\0",
//		SD_SetsUser2_KHarm100_17,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_17\0",
//		SD_SetsUser2_KHarm100_18,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_18\0",
//		SD_SetsUser2_KHarm100_19,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_19\0",
//		SD_SetsUser2_KHarm100_20,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_20\0",
//		SD_SetsUser2_KHarm100_21,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_21\0",
//		SD_SetsUser2_KHarm100_22,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_22\0",
//		SD_SetsUser2_KHarm100_23,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_23\0",
//		SD_SetsUser2_KHarm100_24,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_24\0",
//		SD_SetsUser2_KHarm100_25,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_25\0",
//		SD_SetsUser2_KHarm100_26,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_26\0",
//		SD_SetsUser2_KHarm100_27,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_27\0",
//		SD_SetsUser2_KHarm100_28,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_28\0",
//		SD_SetsUser2_KHarm100_29,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_29\0",
//		SD_SetsUser2_KHarm100_30,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_30\0",
//		SD_SetsUser2_KHarm100_31,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_31\0",
//		SD_SetsUser2_KHarm100_32,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_32\0",
//		SD_SetsUser2_KHarm100_33,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_33\0",
//		SD_SetsUser2_KHarm100_34,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_34\0",
//		SD_SetsUser2_KHarm100_35,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_35\0",
//		SD_SetsUser2_KHarm100_36,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_36\0",
//		SD_SetsUser2_KHarm100_37,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_37\0",
//		SD_SetsUser2_KHarm100_38,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_38\0",
//		SD_SetsUser2_KHarm100_39,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_39\0",
//		SD_SetsUser2_KHarm100_40,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarm100_40\0",
//
//		SD_SetsUser2_KHarmTotal95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarmTotal95\0",
//		SD_SetsUser2_KHarmTotal100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_KHarmTotal100\0",
//		SD_SetsUser2_K2U95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_K2U95\0",
//		SD_SetsUser2_K2U100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_K2U100\0",
//		SD_SetsUser2_K0U95,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_K0U95\0",
//		SD_SetsUser2_K0U100,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_K0U100\0",
//		SD_SetsUser2_CheckSum,
//			SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_CheckSum\0",
////}
//
//	SD_CalibrationUpdate,
//		SDTYPE_COMMAND,SDACCESS_USER,"SD_CalibrationUpdate\0",
//	SD_RangeUpdate,
//		SDTYPE_COMMAND,SDACCESS_USER,"SD_RangeUpdate\0",
//	SD_FirmwareVersion,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_FirmwareVersion\0",
//
//
//	SD_RegistrationMode,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RegistrationMode\0",
//	SD_RegistrationScheduledStartDateTime,
//		SDTYPE_DATETIME,SDACCESS_USER,"SD_RegistrationScheduledStartDateTime\0",
//	SD_RegistrationScheduledStopDateTime,
//		SDTYPE_DATETIME,SDACCESS_USER,"SD_RegistrationScheduledStopDateTime\0",
//	SD_RegistrationManualStart,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_RegistrationManualStart\0",
//	SD_RegistrationManualStartDateTime,
//		SDTYPE_DATETIME,SDACCESS_USER,"SD_RegistrationManualStartDateTime\0",
//
//	SD_FirmwareIteration,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_FirmwareIteration\0",
//
//	SD_RegistrationArchiveIntervals,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_RegistrationArchiveIntervals\0",
//
//	SD_RegistrationIndex,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_RegistrationIndex\0",
//
//	SD_Password1stLevelHash,
//		SDTYPE_WORD,SDACCESS_READONLY,"SD_Password1stLevelHash\0",
//	SD_Password2ndLevelHash,
//		SDTYPE_WORD,SDACCESS_READONLY,"SD_Password2ndLevelHash\0",
//	SD_MenuAutomaticLock,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_MenuAutomaticLock\0",
//
//	SD_FirmwareVersionBootloader,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_FirmwareVersionBootloader\0",
//
//	SD_NandInvalidBlockCounter,
//		SDTYPE_WORD,SDACCESS_READONLY,"SD_NandInvalidBlockCounter\0",
//	SD_RegistrationArchiveIndex,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_RegistrationArchiveIndex\0",
//
//	SD_RegistrationArchiveLengthSec1,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_RegistrationArchiveLengthSec1\0",
//	SD_RegistrationArchiveLengthSec2,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_RegistrationArchiveLengthSec2\0",
//
//	SD_UsbTraceEnable,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_UsbTraceEnable\0",
//
//	SD_AverageArchiveIndex_3Sec,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_AverageArchiveIndex_3Sec\0",
//	SD_AverageArchiveIndex_10Min,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_AverageArchiveIndex_10Min\0",
//	SD_AverageArchiveIndex_2Hour,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_AverageArchiveIndex_2Hour\0",
//
//	SD_DspSupervisor,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_DspSupervisor\0",
//
//	SD_SetsUser1_VoltageDeviationNegative95,
//		SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_VoltageDeviationNegative95\0",
//	SD_SetsUser1_VoltageDeviationNegative100,
//		SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser1_VoltageDeviationNegative100\0",
//	SD_SetsUser2_VoltageDeviationNegative95,
//		SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_VoltageDeviationNegative95\0",
//	SD_SetsUser2_VoltageDeviationNegative100,
//		SDTYPE_LONG,SDACCESS_USER,"SD_SetsUser2_VoltageDeviationNegative100\0",
//
//	SD_MenuLanguage,	
//		SDTYPE_ENUM,SDACCESS_USER,"SD_MenuLanguage\0",
//	SD_EnegryArchiveIndex,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_EnegryArchiveIndex\0",
//	SD_PasswordEnable,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_PasswordEnable\0",
//
//	SD_SynchroMeasurements_Duration,
//		SDTYPE_WORD,SDACCESS_READONLY,"SD_SynchroMeasurements_Duration\0",
//	SD_SynchroMeasurements_StartDateTime,
//		SDTYPE_DATETIME,SDACCESS_READONLY,"SD_SynchroMeasurements_StartDateTime\0",
//
//	SD_SynchroMeasurementsArchiveIndex,
//		SDTYPE_DWORD,SDACCESS_READONLY,"SD_SynchroMeasurementsArchiveIndex\0",
//
//	SD_FlexClampsSelfPowered,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_FlexClampsSelfPowered\0",
//
//	SD_LanguageChangeEnable,
//		SDTYPE_BOOL,SDACCESS_MARSENERGO,"SD_LanguageChangeEnable\0",
//
//	SD_Flickermeter,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_Flickermeter\0",
//
//	SD_Password0thLevelHash,
//		SDTYPE_WORD,SDACCESS_READONLY,"SD_Password0thLevelHash\0",
//
//	SD_UsbModule_Interface,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_UsbModule_Interface\0",
//	SD_UsbModule_LAN_AddressMode,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_UsbModule_LAN_AddressMode\0",
//	SD_UsbModule_WLAN_AddressMode,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_UsbModule_WLAN_AddressMode\0",
//	SD_UsbModule_WLAN_Mode,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_UsbModule_WLAN_Mode\0",
//	SD_UsbModule_WLAN_AP_Passphrase,
//		SDTYPE_CHAR16,SDACCESS_USER,"SD_UsbModule_WLAN_AP_Passphrase\0",
//	SD_UsbModule_WLAN_AP_IP,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_UsbModule_WLAN_AP_IP\0",
//	SD_UsbModule_WLAN_AP_Mask,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_UsbModule_WLAN_AP_Mask\0",
//	SD_UsbModule_WLAN_AP_DhcpStart,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_UsbModule_WLAN_AP_DhcpStart\0",
//	SD_UsbModule_WLAN_AP_DhcpEnd,
//		SDTYPE_DWORD,SDACCESS_USER,"SD_UsbModule_WLAN_AP_DhcpEnd\0",
//
//	SD_DeviceClass,
//		SDTYPE_ENUM,SDACCESS_USER,"SD_DeviceClass\0",
//
//	SD_UsbModule_WLAN_Client_Ssid,
//		SDTYPE_SZ64,SDACCESS_USER,"SD_UsbModule_WLAN_Client_Ssid\0",
//	SD_UsbModule_WLAN_Client_Passphrase,
//		SDTYPE_SZ64,SDACCESS_USER,"SD_UsbModule_WLAN_Client_Passphrase\0",
//
//	SD_FlaggedData,
//		SDTYPE_BOOL,SDACCESS_USER,"SD_FlaggedData\0",
//};
//==================================================================================
//==================================================================================
typedef struct 
{
	WORD wUtcDate;
	WORD wUtcMonth;
	WORD wUtcYear;
	WORD wUtcHours;
	WORD wUtcMinutes;
	WORD wUtcSeconds;
		WORD wLocalDate;
		WORD wLocalMonth;
		WORD wLocalYear;
		WORD wLocalHours;
		WORD wLocalMinutes;
		WORD wLocalSeconds;
	WORD wMilliseconds;
	WORD wTimeZone;
} TDateTime;
//==================================================================================
//==================================================================================

#endif
