//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmServiceLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class emstrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal emstrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmService.emstrings", typeof(emstrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send letter to the support service.
        /// </summary>
        internal static string msg_error_send_logs {
            get {
                return ResourceManager.GetString("msg_error_send_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error while sending letter to the support service.
        /// </summary>
        internal static string msg_error2_send_logs {
            get {
                return ResourceManager.GetString("msg_error2_send_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs were sent successfully.
        /// </summary>
        internal static string msg_logs_were_sent {
            get {
                return ResourceManager.GetString("msg_logs_were_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        internal static string name_avg_time_10min_full {
            get {
                return ResourceManager.GetString("name_avg_time_10min_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string name_avg_time_2hour_full {
            get {
                return ResourceManager.GetString("name_avg_time_2hour_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 seconds (150/180 periods).
        /// </summary>
        internal static string name_avg_time_3sec_full {
            get {
                return ResourceManager.GetString("name_avg_time_3sec_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-phase, two-wire.
        /// </summary>
        internal static string name_con_scheme_Ph1W2_full {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph1W2_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1hp 2w.
        /// </summary>
        internal static string name_con_scheme_Ph1W2_short {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph1W2_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-phase, three-wire (2 element).
        /// </summary>
        internal static string name_con_scheme_Ph3W3_B_calc_full {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W3_B_calc_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3hp 3w (2-elem.).
        /// </summary>
        internal static string name_con_scheme_Ph3W3_B_calc_short {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W3_B_calc_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-phase, three-wire (3 element).
        /// </summary>
        internal static string name_con_scheme_Ph3W3_full {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W3_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3hp 3w (3-elem.).
        /// </summary>
        internal static string name_con_scheme_Ph3W3_short {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W3_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-phase, four-wire.
        /// </summary>
        internal static string name_con_scheme_Ph3W4_B_calc_full {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W4_B_calc_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ph 4w.
        /// </summary>
        internal static string name_con_scheme_Ph3W4_B_calc_short {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W4_B_calc_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-phase, four-wire.
        /// </summary>
        internal static string name_con_scheme_Ph3W4_full {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W4_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ph 4w.
        /// </summary>
        internal static string name_con_scheme_Ph3W4_short {
            get {
                return ResourceManager.GetString("name_con_scheme_Ph3W4_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 1 (0.38 кV).
        /// </summary>
        internal static string name_constraint_type_pqpa_1_full {
            get {
                return ResourceManager.GetString("name_constraint_type_pqpa_1_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 2 (6-25 кV).
        /// </summary>
        internal static string name_constraint_type_pqpa_2_full {
            get {
                return ResourceManager.GetString("name_constraint_type_pqpa_2_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 3 (35 кV).
        /// </summary>
        internal static string name_constraint_type_pqpa_3_full {
            get {
                return ResourceManager.GetString("name_constraint_type_pqpa_3_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 4 (110-220 кV).
        /// </summary>
        internal static string name_constraint_type_pqpa_4_full {
            get {
                return ResourceManager.GetString("name_constraint_type_pqpa_4_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User set 1.
        /// </summary>
        internal static string name_constraint_type_pqpa_5_full {
            get {
                return ResourceManager.GetString("name_constraint_type_pqpa_5_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User set 2.
        /// </summary>
        internal static string name_constraint_type_pqpa_6_full {
            get {
                return ResourceManager.GetString("name_constraint_type_pqpa_6_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string ok_caption {
            get {
                return ResourceManager.GetString("ok_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is invalid!.
        /// </summary>
        internal static string str_invalid_email {
            get {
                return ResourceManager.GetString("str_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to fill in &quot;E-mail&quot; field.
        /// </summary>
        internal static string str_no_email {
            get {
                return ResourceManager.GetString("str_no_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to fill in &quot;Sender&quot; field.
        /// </summary>
        internal static string str_no_sender {
            get {
                return ResourceManager.GetString("str_no_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately.
        /// </summary>
        internal static string unfortunately_caption {
            get {
                return ResourceManager.GetString("unfortunately_caption", resourceCulture);
            }
        }
    }
}
